### ISSUE TITLE
NameError: name 't' is not defined

### ISSUE THREAD

**Issue by reith** [sarugaku/plette#58]
https://github.com/sarugaku/plette/blob/8e2232780c2e50c7026dfec31e8db3f436b271ad/src/plette/models/scripts.py#L28

Not sure what the code should look like.. Pipenv 2024.0.0 release broke our builds throwing this name error.

**Comment by oz123** [comment]
Can you please share your pipfile with us? 
The script section should be included.

**Comment by reith** [comment]
@oz123 here you go: https://github.com/reith/plette-58/blob/master/Pipfile

**Comment by oz123** [comment]
Thanks for sharing your file.

**Comment by oz123** [comment]
So, apparently this is a documented feature of pipenv (but not found in plette before as tests or docs).

https://pipenv.pypa.io/en/latest/scripts.html?highlight=scripts
